plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Shamrat Kumar Paul
description: This is my Jekyll website that is running Simple.css
lang: en
locale: en_GB
url: "https://paulshamrat.github.io"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20